image: ubuntu:yakkety

before_script:
    - apt-get update -qq && apt-get install --yes -qq libboost-program-options1.61.0

stages:
    - build
    - test
    - deploy

build:gcc:
    stage: build
    script: 
        - apt-get install --yes -qq scons gcc g++ cmake libboost-program-options1.61-dev git
        - git submodule update --init
        - scons compiler=gcc mode=debug
        - scons compiler=gcc mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

build:clang:
    stage: build
    script: 
        - apt-get install --yes -qq scons clang cmake libboost-program-options1.61-dev git
        - git submodule update --init
        - scons compiler=clang mode=debug
        - scons compiler=clang mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

build:arch:
    image: logankoester/archlinux
    stage: build
    before_script:
        - pacman -Syu --no-confirm
        - pacman -S --no-confirm scons gcc g++ cmake boost boost-libs git
    script:
        - scons compiler=gcc mode=debug
        - scons compiler=gcc mode=release
        - scons compiler=clang mode=debug
        - scons compiler=clang mode=release

unittest-core:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/core/core-unittest

unittest-yaml:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/yaml/yaml-unittest

unittest-config:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/config/config-unittest

unittest-plugins:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/plugins/plugins-unittest

unittest-commander:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/commander/commander-unittest

memory-check:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes valgrind make
        - make check-memory

coverage:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes lcov make
        - make coverage
    artifacts:
        paths:
            - test_coverage/

pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mkdir public && mv test_coverage/ public/coverage
    artifacts:
        paths:
            - public
        expire_in: 30 days
