image: scratch

stages:
    - build-image
    - build-native
    - build
    - test
    - analyze
    - deploy

variables:
    ALL_RUN_TARGETS: unittest integration
    ALL_MODULES: log config yaml core commander plugins
    ALL_SOURCE_TYPES: src test
    DOCKER_DRIVER: overlay2         # Overwrite default docker driver

.build_tools: &build_tools
        ":"           # Delegated to docker images

.install_exec_helper: &install_exec_helper
        sudo cp build/native/release/src/applications/exec-helper /usr/local/bin/

.run_test: &run_test
    stage: test
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-run
    variables:
        RUN_TARGET: $ALL_RUN_TARGETS
        MODULES: $ALL_MODULES
        NB_RUNS: 1000
    dependencies:
        - build:native
        - build:gcc
        - build:clang
    script:
        - *install_exec_helper
        - export PATH=$(pwd)/build/g++/release/install/bin:$(pwd)/build/g++/release/install/test/integration:$PATH
        - echo "using run target '$RUN_TARGET'"
        - echo "using modules '$MODULES'"
        - export RC_PARAMS="max_success=${NB_RUNS} max_size=${NB_RUNS}"
        - exec-helper run-test --run-target $RUN_TARGET --module $MODULES --compiler g++ clang++ --mode release --debug debug

.memory-check: &memory_check
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    variables:
        MODULES: $ALL_MODULES
        RUN_TARGET: $ALL_RUN_TARGETS
    dependencies:
        - build:native
        - build:gcc:limited-optimization
    script:
        - *install_exec_helper
        - export PATH=$(pwd)/build/g++/limited/install/bin:$(pwd)/build/g++/limited/install/test/integration:$PATH
        - exec-helper analyze --analyze valgrind --run-target $RUN_TARGET --compiler g++ --mode limited --module $MODULES

.clang_tidy: &clang_tidy
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    variables:
        MODULES: $ALL_MODULES
        SOURCE_TYPE: $ALL_SOURCE_TYPES
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - exec-helper setup init-build -c g++ -m release
        - exec-helper analyze --analyze clang-tidy --module $MODULES --source-type $SOURCE_TYPE

.cppcheck: &cppcheck
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    variables:
        SOURCE_TYPE: $ALL_SOURCE_TYPES
        MODULES: $ALL_MODULES
    dependencies:
        - build:native
    script:
        - *install_exec_helper
        - exec-helper analyze --analyze cppcheck --source-type $SOURCE_TYPE --module $MODULES

.undefined_behaviour: &undefined_behaviour
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    variables:
        RUN_TARGET: $ALL_RUN_TARGETS
        MODULES: $ALL_MODULES
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - export PATH=$(pwd)/build/clang++/undefined-behaviour/install/bin:$(pwd)/build/clang++/undefined-behaviour/install/test/integration:$PATH
        - exec-helper undefined-behaviour

.code_format: &code_format
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    dependencies:
        - build:native
    variables:
        MODULES: $ALL_MODULES
        SOURCE_TYPE: $ALL_SOURCE_TYPES
    script:
        - *install_exec_helper
        - exec-helper analyze -a format

.asan: &asan_check
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    variables:
        MODULES: $ALL_MODULES
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - export PATH=$(pwd)/build/clang++/asan/install/bin:$(pwd)/build/clang++/asan/install/test/integration:$PATH
        - exec-helper analyze --analyze asan --module "${ALL_MODULES}"      # Note: the quotes are used to cheat exec-helper so that the binaries are only built once rather than for each module separately

.build_image: &build_image
    stage: build-image
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE: blaat
        WORKDIR: docker
    script:
        - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
        - echo "Building image '${IMAGE}'"
        - cd ${WORKDIR}
        - docker build --compress=true --force-rm=true --pull=true --no-cache=true --rm=true --tag="${IMAGE}" .
        - docker push ${IMAGE}

build-image:analyze:
    <<: *build_image
    variables:
        IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
        WORKDIR: docker/analyze

build-image:build:
    <<: *build_image
    variables:
        IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
        WORKDIR: docker/build

build-image:build-debian:
    stage: build-image
    image: docker:latest
    services:
        - docker:dind
    variables:
        BUILD_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build-debian
    before_script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    script:
        - echo "Building image '$BUILD_IMAGE'"
        - cd docker/build
        - docker build -t ${BUILD_IMAGE} -f debian.Dockerfile .
        - docker push ${BUILD_IMAGE}

build-image:run:
    <<: *build_image
    variables:
        IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-run
        WORKDIR: docker/run

build:native:
    stage: build-native
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
    dependencies: []
    script:
        - *build_tools
        - make
        - sudo make install
    artifacts:
        expire_in: 1 day
        paths:
            - build/native/release/src/applications/exec-helper

build:debian:
    stage: build-native
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build-debian
    dependencies: []
    script:
        - make BUILD_DOCUMENTATION=OFF binary
        - make install-bin
    artifacts:
        expire_in: 1 day
        paths:
            - build/native/release/src/applications/exec-helper

build:no-system:
    stage: build
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-run
    dependencies:
        - build:native
    before_script:
        - sudo pacman -Sy --needed --noconfirm clang cmake make doxygen git
    script: 
        - *build_tools
        - *install_exec_helper
        - exec-helper init-no-system build --compiler clang++ --mode release

build:gcc:
    stage: build
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - exec-helper init build --compiler g++ --mode release
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/release/install

build:gcc:debug:
    stage: build
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - exec-helper init build --compiler g++ --mode debug

build:gcc:limited-optimization:
    stage: build
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        - exec-helper init-limited-optimization build --compiler g++ --mode limited
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/limited/install

build:clang:
    stage: build
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build
    dependencies:
        - build:native
    script: 
        - *build_tools
        - *install_exec_helper
        - exec-helper init build --compiler clang++ --mode release
    artifacts:
        expire_in: 1 day
        paths:
            - build/clang++/release/install

unittests:
    <<: *run_test
    variables:
        RUN_TARGET: unittest
        MODULES: log config yaml commander
        NB_RUNS: 1000

unittests-core:
    <<: *run_test
    variables:
        RUN_TARGET: unittest
        MODULES: core plugins
        NB_RUNS: 100
    before_script:
        - ulimit -n

integration:
    <<: *run_test
    variables:
        RUN_TARGET: integration
    before_script:
        - sudo pacman -Sy --needed --noconfirm python python-pip
        - sudo pip install -r test/integration/requirements.txt
    after_script:
        - mkdir -p integration
        - mv build/g++/release/*.{xml,html} integration/
    artifacts:
        expire_in: 1 day
        paths:
            - integration/*

memory-check:
    <<: *memory_check
    variables:
        RUN_TARGET: unittest integration-old
        MODULES: $ALL_MODULES

clang-tidy:
    <<: *clang_tidy

clang-tidy-integration:
    <<: *clang_tidy
    variables:
        SOURCE_TYPE: test
        MODULES: integration

clang-static-analyzer:
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    dependencies:
        - build:native
    script:
        - *build_tools
        - *install_exec_helper
        # Ugly hack for circumventing issues with the (unused) scan-build c compiler.
        - echo "SET(CMAKE_C_COMPILER  clang)" >> toolchain.cmake.in
        - exec-helper analyze --analyze clang-static-analyzer --mode debug --compiler ''

cross-compilation:
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-build-debian
    dependencies:
        - build:debian
    before_script:
        - *install_exec_helper
    script:
        - apt-get install --yes debootstrap g++-aarch64-linux-gnu cmake ninja-build pkg-config git
        - debootstrap --arch=arm64 --foreign --variant=minbase --include=libboost-program-options-dev,libboost-filesystem-dev,libboost-log-dev,doxygen,libc6-dev testing ./sysroot_arm64 http://deb.debian.org/debian/
        - for DEB in $(find sysroot_arm64/var/cache/apt/archives -not -path sysroot_arm64/var/cache/apt/archives/partial -type f); do echo "Extracting ${DEB}..."; dpkg -x ${DEB} sysroot_arm64; done   # Unpack all downloaded debian packages, since debootstrap does not seem to unpack the additional included ones and their dependencies
        - exec-helper init-no-system build --compiler aarch64-linux-gnu-g++ --mode release --sysroot $(pwd)/sysroot_arm64

undefined-behaviour:
    <<: *undefined_behaviour

address-sanitizer:
    <<: *asan_check

coverage:
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    dependencies:
        - build:native
        - build:gcc
    script:
        - *build_tools
        - *install_exec_helper
        - export PATH=$(pwd)/build/g++/release/install/bin:$(pwd)/build/g++/release/install/test/integration:$PATH
        - exec-helper coverage
    artifacts:
        paths:
            - test_coverage/

cppcheck-unittest:
    <<: *cppcheck
    variables:
        SOURCE_TYPE: src
        MODULES: $ALL_MODULES

code-duplication-pmd-cpd:
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    dependencies:
        - build:native
    script:
        - *install_exec_helper
        - exec-helper analyze --analyze pmd
        - exec-helper analyze --analyze pmd --module integration --source-type test

#coverity:
    #stage: analyze
    #image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    #variables:
        #COVERITY_ARCHIVE_NAME: exec-helper_${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}.xz
    #dependencies:
        #- build:native
    #script:
        #- *build_tools
        #- *install_exec_helper
        #- curl --data "token=${COVERITY_SCAN_TOKEN}&project=bverhagen%2Fexec-helper" https://scan.coverity.com/download/cxx/linux64 -o coverity_tool.tgz
        #- tar -C /tmp -xf coverity_tool.tgz
        #- pushd /tmp/cov-analysis-linux64-*/bin
        #- export PATH=$PATH:$(pwd)
        #- popd
        #- exec-helper distclean analyze --analyze coverity --compiler g++ --mode release --coverity-archive-name $COVERITY_ARCHIVE_NAME
        #- curl --form token=${COVERITY_SCAN_TOKEN} --form email=barrie.verhagen@gmail.com --form file=@${COVERITY_ARCHIVE_NAME} --form version="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}" --form description="Analysis scan for ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}" https://scan.coverity.com/builds?project=bverhagen%2Fexec-helper
    #only:
        #- master
        #- dev

examples:
    stage: analyze
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-analyze
    dependencies:
        - build:native
    script:
        - *install_exec_helper
        - export ROOT_DIR=$(pwd)
        - cd ${ROOT_DIR}/src/config/examples
        - exec-helper --settings-file exec-helper-config.example build clean rebuild
        - exec-helper --settings-file exec-helper-config-environment.example example
        - cd ${ROOT_DIR}/src/plugins/examples
        - exec-helper --settings-file command-line-command.example example
        - exec-helper --settings-file selector.example example
        - exec-helper --settings-file bootstrap.example example
        - exec-helper --settings-file make.example example
        - exec-helper --settings-file ninja.example example
        - exec-helper --settings-file scons.example example
        - exec-helper --settings-file clang-static-analyzer.example example
        - exec-helper --settings-file clang-tidy.example example
        - exec-helper --settings-file cppcheck.example example
        - exec-helper --settings-file lcov.example example
        - exec-helper --settings-file pmd.example example
        - exec-helper --settings-file valgrind.example example

code-format:
    <<: *code_format

pages:
    stage: deploy
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-run
    dependencies:
        - coverage
        - build:gcc
        - integration
    script:
        - mkdir public
        - mv pages/index.html public/
        - mv test_coverage/ public/coverage
        - mkdir -p public/docs
        - mv build/g++/release/install/share/doc/exec-helper/html public/docs/
        - mv integration public/integration
    artifacts:
        paths:
            - public
    only:
        - master
