stages:
    - build
    - test

build:gcc:
    stage: build
    before_script:
        - apt-get install --yes -qq scons gcc g++ cmake libboost-program-options1.55-dev libboost-program-options1.55.0
        - git submodule update --init
    script: 
        - scons compiler=gcc mode=debug
        - scons compiler=gcc mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

unittest-core:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/core/core-unittest

memory-check:
    stage: test
    dependencies:
        - build:gcc
    before_script:
        - apt-get install valgrind
    script:
        - make check-memory

coverage:
    stage: test
    dependencies:
        - build:gcc
    before_script:
        - apt-get install lcov
    script:
        - make coverage
