image: dock0/arch

before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm --needed boost boost-libs yaml-cpp

stages:
    - build
    - test
    - deploy

build:gcc:
    stage: build
    script:
        - pacman -S --noconfirm --needed gcc cmake make git libunistring ncurses
        - cmake -H. -Bbuild/g++/debug -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/debug -DCMAKE_BUILD_TYPE=Debug -DUSE_SYSTEM_CATCH=OFF && make -C build/g++/debug --jobs 4 && make -C build/g++/debug install
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF && make -C build/g++/release --jobs 4 && make -C build/g++/release install
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/debug/bin
            - build/g++/debug/lib
            - build/g++/release/bin
            - build/g++/release/lib

build:gcc:limited-optimization:
    stage: build
    script:
        - pacman -S --noconfirm --needed gcc cmake make git libunistring ncurses
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF -DLIMITED_OPTIMIZATION=ON && make -C build/g++/release --jobs 4 && make -C build/g++/release install
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/release/bin
            - build/g++/release/lib

build:clang:
    stage: build
    script: 
        - pacman -S --noconfirm --needed clang cmake make git libunistring ncurses
        - cmake -H. -Bbuild/clang++/debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/debug -DCMAKE_BUILD_TYPE=Debug -DUSE_SYSTEM_CATCH=OFF
        - cmake -H. -Bbuild/clang++/release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF
    artifacts:
        expire_in: 1 day
        paths:
            - build/clang++/debug/bin
            - build/clang++/debug/lib
            - build/clang++/release/bin
            - build/clang++/release/lib

test-distribution:ubuntu-yakkety:
    image: ubuntu:yakkety
    stage: test
    before_script:
        - apt-get update
        - apt-get install --yes build-essential cmake make gcc g++ clang libboost-program-options-dev libyaml-cpp-dev git
        # Workaround for issue with cmake thinking make is in the /usr/sbin directory
        - ln -fs /usr/bin/make /usr/sbin/make
        - which make
        - ls -l /usr/sbin
    script:
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF
        - cmake -H. -Bbuild/clang++/release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF

unittest-core:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/g++/release/bin/exec-helper run-test --module core --run-target unittest --compiler g++ --mode release

unittest-yaml:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/g++/release/bin/exec-helper run-test --module yaml --run-target unittest --compiler g++ --mode release

unittest-config:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/g++/release/bin/exec-helper run-test --module config --run-target unittest --compiler g++ --mode release

unittest-plugins:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/g++/release/bin/exec-helper run-test --module plugins --run-target unittest --compiler g++ --mode release

unittest-commander:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/g++/release/bin/exec-helper run-test --module commander --run-target unittest --compiler g++ --mode release

memory-check:
    stage: test
    dependencies:
        - build:gcc:limited-optimization
    script:
        - pacman -S --noconfirm valgrind
        - build/g++/release/bin/exec-helper analyze --analyze valgrind --run-target unittest --compiler g++ --mode release --module core yaml config commander

memory-check-plugins:
    stage: test
    dependencies:
        - build:gcc:limited-optimization
    script:
        - pacman -S --noconfirm valgrind
        - build/g++/release/bin/exec-helper analyze --analyze valgrind --run-target unittest --compiler g++ --mode release --module plugins

cppcheck:
    stage: test
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm cppcheck
        - build/g++/release/bin/exec-helper analyze --analyze cppcheck

clang-static-analyzer:
    stage: test
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed clang cmake make git libunistring ncurses
        - build/g++/release/bin/exec-helper analyze --analyze clang-static-analyzer --mode debug --compiler '$CC'

code-duplication-pmd-cpd:
    stage: test
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed java-environment unzip wget
        - mkdir -p 3rdparty/pmd
        - pushd 3rdparty/pmd && wget --no-check-certificate "https://downloads.sourceforge.net/project/pmd/pmd/5.5.4/pmd-bin-5.5.4.zip" && unzip pmd-bin-5.5.4.zip; popd
        - build/g++/release/bin/exec-helper analyze --analyze pmd

coverage:
    stage: test
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed base-devel curl gcc cmake make git libunistring ncurses
        - bash -x gitlab/install-aur.sh lcov
        - export PATH=$PATH:build/g++/release/bin
        - build/g++/release/bin/exec-helper coverage
    artifacts:
        paths:
            - test_coverage/

pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mkdir public
        - mv pages/index.html public/
        - mv test_coverage/ public/coverage
    artifacts:
        paths:
            - public
        expire_in: 30 days
