before_script:
    - apt-get update -qq && apt-get install --yes -qq libboost-program-options1.55.0

stages:
    - build
    - test
    - deploy

build:gcc:
    stage: build
    script: 
        - apt-get install --yes -qq scons gcc g++ cmake libboost-program-options1.55-dev
        - git submodule update --init
        - scons compiler=gcc mode=debug
        - scons compiler=gcc mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

unittest-core:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/core/core-unittest

unittest-yaml:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/yaml/yaml-unittest

unittest-config:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/config/config-unittest

unittest-plugins:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/plugins/plugins-unittest

unittest-commander:gcc:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/test/commander/commander-unittest

memory-check:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes valgrind
        - make check-memory

coverage:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes lcov
        - make coverage
     artifacts:
         paths:
            - test_coverage/

pages:
	stage: deploy
  	dependencies:
    	- coverage
  	script:
    	- mv test_coverage/ public/
  	artifacts:
    	paths:
      		- public
 		expire_in: 30 days
	only:
    	- generalize-approach
