image: ubuntu:yakkety

before_script:
    - apt-get update -qq && apt-get install --yes -qq libboost-program-options1.61.0

stages:
    - build
    - test
    - deploy

build:gcc:
    stage: build
    script: 
        - apt-get install --yes -qq scons gcc g++ cmake libboost-program-options1.61-dev git
        - git submodule update --init
        - scons -j8 compiler=gcc mode=debug
        - scons -j8 compiler=gcc mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

build:clang:
    stage: build
    script: 
        - apt-get install --yes -qq scons clang cmake libboost-program-options1.61-dev git
        - git submodule update --init
        - scons -j8 compiler=clang mode=debug
        - scons -j8 compiler=clang mode=release
    artifacts:
        expire_in: 1 day
        paths:
            - build/

test-distribution:arch-linux:
    image: dock0/arch
    stage: test
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S --noconfirm scons gcc clang cmake make boost boost-libs git libunistring ncurses
        - git submodule update --init
    script:
        - scons -j8 compiler=gcc mode=debug
        - scons -j8 compiler=gcc mode=release
        - scons -j8 compiler=clang mode=debug
        - scons -j8 compiler=clang mode=release

unittest-core:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/bin/exec-helper run-test --target core --compiler gcc --mode release

unittest-yaml:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/bin/exec-helper run-test --target yaml --compiler gcc --mode release

unittest-config:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/bin/exec-helper run-test --target config --compiler gcc --mode release

unittest-plugins:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/bin/exec-helper run-test --target plugins --compiler gcc --mode release

unittest-commander:
    stage: test
    dependencies:
        - build:gcc
    script:
        - build/gcc/release/bin/exec-helper run-test --target commander --compiler gcc --mode release

memory-check:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes valgrind make
        - make check-memory

cppcheck:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes cppcheck
        - build/gcc/release/bin/exec-helper analyze --analyze cppcheck

clang-static-analyzer:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes -qq scons clang cmake libboost-program-options1.61-dev git
        - git submodule update --init
        - build/gcc/release/bin/exec-helper analyze --analyze clang-static-analyzer --compiler clang --mode debug

coverage:
    stage: test
    dependencies:
        - build:gcc
    script:
        - apt-get install --yes lcov make
        - make coverage
    artifacts:
        paths:
            - test_coverage/

pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mkdir public
        - mv pages/index.html public/
        - mv test_coverage/ public/coverage
    artifacts:
        paths:
            - public
        expire_in: 30 days
