before_script:
    - apt-get update -qq && apt-get install --yes -qq scons gcc clang python3

stages:
    - test

test-distcleanTarget-python2:
    script: "python3 test/distcleanTargetTest.py --compiler gcc clang --python-version python2"
    stage: test

test-distcleanTarget-python3:
    script: "python3 test/distcleanTargetTest.py --compiler gcc clang --python-version python3"
    stage: test

test-buildTarget-python2:
    script: "python3 test/buildTargetTest.py --compiler gcc clang --python-version python2"
    stage: test

test-buildTarget-python3:
    script: "python3 test/buildTargetTest.py --compiler gcc clang --python-version python3"
    stage: test

python2-compatibility:
    script:
        - apt-get install --yes -qq valgrind cppcheck
        - cd example
        - "python2 exec distclean clean init build run rebuild analyze profile -m release -t all -r all -c gcc clang -a clang cppcheck -l callgrind -i exec-helper_profiles.py"
    stage: test

python3-compatibility:
    script:
        - apt-get install --yes -qq valgrind cppcheck
        - cd example
        - "python3 exec distclean clean init build run rebuild analyze profile -m release -t all -r all -c gcc clang -a clang cppcheck -l callgrind -i exec-helper_profiles.py"
    stage: test

python2-perf:
    script:
        - apt-get install --yes -qq unzip default-jre unzip flex bison
        - wget https://github.com/torvalds/linux/archive/master.zip && unzip master.zip && pushd linux-master/tools/perf && make && export PATH=$PATH:$(pwd); popd
        - cd example
        - "python2 exec distclean clean init build run rebuild analyze profile -m release -t all -r all -c gcc clang -l perf -i exec-helper_profiles.py"

python3-perf:
    script:
        - apt-get install --yes -qq unzip default-jre unzip flex bison
        - wget https://github.com/torvalds/linux/archive/master.zip && unzip master.zip && pushd linux-master/tools/perf && make && export PATH=$PATH:$(pwd); popd
        - cd example
        - "python3 exec distclean clean init build run rebuild analyze profile -m release -t all -r all -c gcc clang -l perf -i exec-helper_profiles.py"
