image: dock0/arch

.prepare: &prepare
        pacman -Sy --noconfirm

.install_exec_helper: &install_exec_helper
        pacman -S --noconfirm --needed boost boost-libs yaml-cpp make cmake && make install-bin

.prepare_debian: &prepare_debian
        rm -rf /var/lib/apt/lists/* && apt-get update           # Work around for debian mirror issues that often occur on Gitlab

.install_exec_helper_debian: &install_exec_helper_debian
        apt-get install --yes libboost-program-options-dev libboost-filesystem-dev libyaml-cpp-dev make cmake && make install-bin    # Install dev packages so we do not have to keep track of the version numbering in the runtime package names

.unittest: &unittest
    stage: test
    variables:
        MODULES: UNKNOWN
    dependencies:
        - build:gcc
        - build:clang
    script:
        - *install_exec_helper
        - exec-helper run-test --module $MODULES --run-target unittest --compiler g++ clang++ --mode release

.memory-check: &memory_check
    stage: analyze
    variables:
        MODULES: UNKNOWN
    dependencies:
        - build:gcc
        - build:gcc:limited-optimization
    script:
        - pacman -S --noconfirm valgrind
        - *install_exec_helper
        - exec-helper analyze --analyze valgrind --run-target unittest --compiler g++ --mode release --module $MODULES

.clang_tidy: &clang_tidy
    stage: analyze
    variables:
        MODULES: UNKNOWN
    dependencies:
        - build:gcc
    script:
        - pacman -S --needed --noconfirm gcc cmake make pkg-config clang-tools-extra
        - *install_exec_helper
        - exec-helper setup init-build -c g++ -m release
        - make -C build/g++/release/build catch gsl
        - exec-helper analyze --analyze clang-tidy --module $MODULES

before_script:
    - *prepare

stages:
    - build
    - test
    - analyze
    - deploy

build:gcc:
    stage: build
    script:
        - pacman -S --noconfirm --needed boost boost-libs yaml-cpp gcc cmake make doxygen python-pip pkg-config
        - pip install gitchangelog
        - make && make install
        - exec-helper init build --compiler g++ --mode debug release
    artifacts:
        expire_in: 1 day
        paths:
            - build/native
            - build/g++/debug/install
            - build/g++/release/install

build:gcc:limited-optimization:
    stage: build
    script:
        - pacman -S --noconfirm --needed boost boost-libs yaml-cpp gcc cmake make python-pip pkg-config
        - pip install gitchangelog
        - cmake -H. -Bbuild/g++/release/build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release/install -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF -DLIMITED_OPTIMIZATION=ON
        - make -C build/g++/release/build --jobs 4
        - make -C build/g++/release/build install
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/release/install

build:clang:
    stage: build
    script: 
        - pacman -S --noconfirm --needed boost boost-libs yaml-cpp clang cmake make python-pip pkg-config doxygen
        - pip install gitchangelog
        - make && make install
        - exec-helper init build --compiler clang++ --mode debug release
    artifacts:
        expire_in: 1 day
        paths:
            - build/clang++/debug/install
            - build/clang++/release/install

build:debian:
    image: debian:testing
    stage: build
    before_script:
        - *prepare_debian
    script:
        - apt-get install --yes cmake make libboost-dev libboost-program-options-dev libboost-filesystem-dev libyaml-cpp-dev pkg-config g++ git doxygen python-pip
        - pip install gitchangelog
        - make && make install-bin
    artifacts:
        expire_in: 1 day
        paths:
            - build/native/release

unittests:
    <<: *unittest
    variables:
        MODULES: core config yaml commander

unittest-plugins:
    <<: *unittest
    variables:
        MODULES: plugins

memory-check:
    <<: *memory_check
    variables:
        MODULES: core yaml config commander

memory-check-plugins:
    <<: *memory_check
    variables:
        MODULES: plugins

cppcheck:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm cppcheck
        - *install_exec_helper
        - exec-helper analyze --analyze cppcheck

clang-tidy:
    <<: *clang_tidy
    variables:
        MODULES: yaml commander config

clang-tidy-core:
    <<: *clang_tidy
    variables:
        MODULES: core

clang-tidy-plugin:
    <<: *clang_tidy
    variables:
        MODULES: plugin

clang-static-analyzer:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed clang cmake make pkg-config
        - *install_exec_helper
        # Ugly hack for circumventing issues with the (unused) scan-build c compiler.
        - echo "SET(CMAKE_C_COMPILER  clang)" >> toolchain.cmake.in
        - exec-helper analyze --analyze clang-static-analyzer --mode debug --compiler ''

undefined-behaviour:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed clang cmake make pkg-config
        - *install_exec_helper
        - exec-helper undefined-behaviour

code-duplication-pmd-cpd:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed java-environment unzip wget
        - mkdir -p 3rdparty/pmd
        - pushd 3rdparty/pmd && wget --no-check-certificate "https://downloads.sourceforge.net/project/pmd/pmd/5.7.0/pmd-bin-5.7.0.zip" && unzip pmd-bin-5.7.0.zip; popd
        - *install_exec_helper
        - exec-helper analyze --analyze pmd

coverage:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed base-devel curl gcc cmake make pkg-config
        - bash -x gitlab/install-aur.sh lcov
        - *install_exec_helper
        - exec-helper coverage
    artifacts:
        paths:
            - test_coverage/

examples:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed base-devel curl gcc clang make scons clang-tools-extra cppcheck git java-environment unzip wget valgrind
        - bash -x gitlab/install-aur.sh lcov
        - mkdir -p 3rdparty/pmd
        - *install_exec_helper
        - pushd 3rdparty/pmd && wget --no-check-certificate "https://downloads.sourceforge.net/project/pmd/pmd/5.7.0/pmd-bin-5.7.0.zip" && unzip pmd-bin-5.7.0.zip; popd
        - export PATH=$PATH:$(pwd)/3rdparty/pmd/pmd-bin-5.7.0/bin
        - export ROOT_DIR=$(pwd)
        - cd ${ROOT_DIR}/src/config/examples
        - exec-helper --settings-file exec-helper-config.example build clean rebuild
        - exec-helper --settings-file exec-helper-config-environment.example example
        - cd ${ROOT_DIR}/src/plugins/examples
        - exec-helper --settings-file command-line-command.example example
        - exec-helper --settings-file selector.example example
        - exec-helper --settings-file bootstrap.example example
        - exec-helper --settings-file make.example example
        - exec-helper --settings-file scons.example example
        - exec-helper --settings-file clang-static-analyzer.example example
        - exec-helper --settings-file clang-tidy.example example
        - exec-helper --settings-file cppcheck.example example
        - exec-helper --settings-file lcov.example example
        - exec-helper --settings-file pmd.example example
        - exec-helper --settings-file valgrind.example example

cross-compilation:
    image: debian:testing
    stage: analyze
    dependencies:
        - build:debian
    before_script:
        - *prepare_debian
        - *install_exec_helper_debian
    script:
        - apt-get install --yes debootstrap g++-aarch64-linux-gnu cmake make pkg-config git
        - debootstrap --download-only --arch=arm64 --foreign --download-only --variant=minbase --include=libboost-program-options-dev,libboost-filesystem-dev,libyaml-cpp-dev,doxygen,libc6-dev testing ./sysroot_arm64 http://deb.debian.org/debian/
        - for DEB in $(find sysroot_arm64/var/cache/apt/archives -not -path sysroot_arm64/var/cache/apt/archives/partial -type f); do echo "Extracting ${DEB}..."; dpkg -x ${DEB} sysroot_arm64; done   # Unpack all downloaded debian packages, since debootstrap does not seem to unpack the additional included ones and their dependencies
        - exec-helper init-build build --compiler aarch64-linux-gnu-g++ --mode release --sysroot $(pwd)/sysroot_arm64

pages:
    stage: deploy
    dependencies:
        - coverage
        - build:gcc
    script:
        - mkdir public
        - mv pages/index.html public/
        - mv test_coverage/ public/coverage
        - mv build/g++/release/install/share/doc/exec-helper/html public/docs
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
