image: dock0/arch

before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm --needed boost boost-libs yaml-cpp

stages:
    - build
    - test
    - analyze
    - deploy

build:gcc:
    stage: build
    script:
        - pacman -S --noconfirm --needed gcc cmake make git libunistring ncurses
        - cmake -H. -Bbuild/g++/debug -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/debug -DCMAKE_BUILD_TYPE=Debug -DUSE_SYSTEM_CATCH=OFF && make -C build/g++/debug --jobs 4 && make -C build/g++/debug install
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF && make -C build/g++/release --jobs 4 && make -C build/g++/release install
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/debug/bin
            - build/g++/debug/lib
            - build/g++/release/bin
            - build/g++/release/lib

build:gcc:limited-optimization:
    stage: build
    script:
        - pacman -S --noconfirm --needed gcc cmake make git libunistring ncurses
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF -DLIMITED_OPTIMIZATION=ON && make -C build/g++/release --jobs 4 && make -C build/g++/release install
    artifacts:
        expire_in: 1 day
        paths:
            - build/g++/release/bin
            - build/g++/release/lib

build:clang:
    stage: build
    script: 
        - pacman -S --noconfirm --needed clang cmake make git libunistring ncurses
        - cmake -H. -Bbuild/clang++/debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/debug -DCMAKE_BUILD_TYPE=Debug -DUSE_SYSTEM_CATCH=OFF && make -C build/clang++/debug --jobs 4 && make -C build/clang++/debug install
        - cmake -H. -Bbuild/clang++/release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF && make -C build/clang++/release --jobs 4 && make -C build/clang++/release install
    artifacts:
        expire_in: 1 day
        paths:
            - build/clang++/debug/bin
            - build/clang++/debug/lib
            - build/clang++/release/bin
            - build/clang++/release/lib

test-distribution:ubuntu-yakkety:
    image: ubuntu:yakkety
    stage: analyze
    before_script:
        - apt-get update
        - apt-get install --yes build-essential cmake make gcc g++ clang libboost-program-options-dev libyaml-cpp-dev git
        # Workaround for issue with cmake thinking make is in the /usr/sbin directory
        - ln -fs /usr/bin/make /usr/sbin/make
        - which make
        - ls -l /usr/sbin
    script:
        - cmake -H. -Bbuild/g++/release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=build/g++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF
        - cmake -H. -Bbuild/clang++/release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/clang++/release -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_CATCH=OFF

unittest-core:
    stage: test
    dependencies:
        - build:gcc
        - build:clang
    script:
        - build/g++/release/bin/exec-helper run-test --module core --run-target unittest --compiler g++ clang++ --mode release

unittest-yaml:
    stage: test
    dependencies:
        - build:gcc
        - build:clang
    script:
        - build/g++/release/bin/exec-helper run-test --module yaml --run-target unittest --compiler g++ clang++ --mode release

unittest-config:
    stage: test
    dependencies:
        - build:gcc
        - build:clang
    script:
        - build/g++/release/bin/exec-helper run-test --module config --run-target unittest --compiler g++ clang++ --mode release

unittest-plugins:
    stage: test
    dependencies:
        - build:gcc
        - build:clang
    script:
        - build/g++/release/bin/exec-helper run-test --module plugins --run-target unittest --compiler g++ clang++ --mode release

unittest-commander:
    stage: test
    dependencies:
        - build:gcc
        - build:clang
    script:
        - build/g++/release/bin/exec-helper run-test --module commander --run-target unittest --compiler g++ clang++ --mode release

memory-check:
    stage: analyze
    dependencies:
        - build:gcc:limited-optimization
    script:
        - pacman -S --noconfirm valgrind
        - build/g++/release/bin/exec-helper analyze --analyze valgrind --run-target unittest --compiler g++ --mode release --module core yaml config commander

memory-check-plugins:
    stage: analyze
    dependencies:
        - build:gcc:limited-optimization
    script:
        - pacman -S --noconfirm valgrind
        - build/g++/release/bin/exec-helper analyze --analyze valgrind --run-target unittest --compiler g++ --mode release --module plugins

cppcheck:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm cppcheck
        - build/g++/release/bin/exec-helper analyze --analyze cppcheck

clang-tidy-core:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --needed --noconfirm cppcheck gcc cmake make clang-tools-extra
        - build/g++/release/bin/exec-helper setup init -c g++ -m release
        - make -C build/g++/release Catch
        - build/g++/release/bin/exec-helper analyze --analyze clang-tidy --module core

clang-tidy-plugin:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --needed --noconfirm cppcheck gcc cmake make clang-tools-extra
        - build/g++/release/bin/exec-helper setup init -c g++ -m release
        - make -C build/g++/release Catch
        - build/g++/release/bin/exec-helper analyze --analyze clang-tidy --module plugins

clang-tidy-rest:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --needed --noconfirm cppcheck gcc cmake make clang-tools-extra
        - build/g++/release/bin/exec-helper setup init -c g++ -m release
        - make -C build/g++/release Catch
        - build/g++/release/bin/exec-helper analyze --analyze clang-tidy --module yaml commander config

clang-static-analyzer:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed clang cmake make git libunistring ncurses
        - build/g++/release/bin/exec-helper analyze --analyze clang-static-analyzer --mode debug --compiler ''

undefined-behaviour:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed clang cmake make git libunistring ncurses
        - export PATH=$PATH:build/g++/release/bin
        - build/g++/release/bin/exec-helper undefined-behaviour


code-duplication-pmd-cpd:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed java-environment unzip wget
        - mkdir -p 3rdparty/pmd
        - pushd 3rdparty/pmd && wget --no-check-certificate "https://downloads.sourceforge.net/project/pmd/pmd/5.5.4/pmd-bin-5.5.4.zip" && unzip pmd-bin-5.5.4.zip; popd
        - build/g++/release/bin/exec-helper analyze --analyze pmd

coverage:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - pacman -S --noconfirm --needed base-devel curl gcc cmake make git libunistring ncurses
        - bash -x gitlab/install-aur.sh lcov
        - export PATH=$PATH:build/g++/release/bin
        - build/g++/release/bin/exec-helper coverage
    artifacts:
        paths:
            - test_coverage/

docs:
    stage: analyze
    script:
        - pacman -S --noconfirm doxygen
        - build/g++/release/bin/exec-helper docs
    artifacts:
        paths:
            - build/docs/

examples:
    stage: analyze
    dependencies:
        - build:gcc
    script:
        - export PATH=$PATH:$(pwd)/build/g++/release/bin
        - exec-helper --settings-file src/config/examples/exec-helper-config.example build clean rebuild
        - exec-helper --settings-file src/plugins/examples/command-line-command.example example
        - exec-helper --settings-file src/plugins/examples/selector.example example
        - cd src/plugins/examples && exec-helper --settings-file selector.example example

pages:
    stage: deploy
    dependencies:
        - coverage
        - docs
    script:
        - mkdir public
        - mv pages/index.html public/
        - mv test_coverage/ public/coverage
        - mv build/docs public/docs
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - dev
